language: ruby

rvm:
  - 2.2

before_script:
  - gem install awesome_bot

script:
  - awesome_bot FRONT.rst --allow-redirect --allow-ssl --allow-dupe
  - awesome_bot BACK.rst --allow-redirect --allow-ssl --allow-dupe
  - awesome_bot README.md --allow-redirect --allow-ssl --allow-dupe
