on: 
  pull_request:
  push:
    branches:
      - master

name: GitHub Actions
jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
      - name: install
        run: gem install awesome_bot
      - name: check
        run: |
          awesome_bot BADGES.rst --allow-redirect --allow-ssl --allow-dupe -w github.com/srz-zumix/iutest/actions
          awesome_bot BADGES-v.rst --allow-redirect --allow-ssl --allow-dupe -w github.com/srz-zumix/iutest/actions
          awesome_bot LOVECI.rst --allow-redirect --allow-ssl --allow-dupe
          awesome_bot README.md --allow-redirect --allow-ssl --allow-dupe
                
